CREATE TABLE IF NOT EXISTS "networkPerformanceFixed" (
	"idResult" bigint NOT NULL,
	"guidResult" text,
	"idPlatform" smallint,
	"tsResult" timestamp with time zone NOT NULL,
	"tsResultReceived" timestamp with time zone,
	"attrLocationTimezone" text,
	"idDevice" bigint,
	"attrDeviceModel" text,
	"attrDeviceManufacturer" text,
	"attrDeviceManufacturerRaw" text,
	"attrDeviceBrandRaw" text,
	"attrDeviceChipset" text,
	"attrDeviceChipsetManufacturer" text,
	"attrDeviceOsVersion" text,
	"attrDeviceRadio" text,
	"attrDeviceRamMb" integer,
	"attrDeviceStorageMb" integer,
	"attrDeviceSoftwareVersion" text,
	"attrDeviceSystemMemoryMb" integer,
	"attrDeviceProcessorCount" smallint,
	"attrDeviceProcessorType" text,
	"attrDeviceProcessorFrequency" smallint,
	"attrProviderName" text,
	"attrProviderNameCommon" text,
	"attrSimOperatorCommonName" text,
	"attrSimOperatorNameRaw" text,
	"attrSimOperatorMcc" integer,
	"attrSimOperatorMnc" integer,
	"attrNetworkOperatorMcc" integer,
	"attrNetworkOperatorMnc" integer,
	"idConnectionType" smallint,
	"attrConnectionTypeString" text,
	"attrConnectionLinkSpeed" integer,
	"idConnectionNetSpeed" smallint,
	"attrTestMethod" text,
	"attrTestIpVersion" smallint,
	"attrResultTestSource" text,
	"attrBrowserAgent" text,
	"attrLocationLatitude" double precision,
	"attrLocationLongitude" double precision,
	"attrLocationAltitude" integer,
	"attrLocationAccuracyM" integer,
	"attrLocationAgeMs" bigint,
	"idLocationType" smallint,
	"attrPlaceName" text,
	"attrPlaceLocalityType" text,
	"attrPlaceCountry" text,
	"attrPlaceCountryCode" text,
	"attrPlaceRegion" text,
	"attrPlaceSubregion" text,
	"attrPlaceSubsubregion" text,
	"attrPlacePostalCode" text,
	"attrWifiMacManufacturer" text,
	"attrWifiFrequencyMhz" integer,
	"attrWifiChannelWidthMhz" smallint,
	"isWifi5ghz" boolean,
	"isWifi6ghz" boolean,
	"isWifi24ghzBandSupported" boolean,
	"isWifi5ghzSupported" boolean,
	"isWifi6ghzBandSupported" boolean,
	"isWifi60ghzBandSupported" boolean,
	"attrWifiBaseStationId" text,
	"attrWifiRssiDbm" integer,
	"attrWifiRxLinkSpeedMbps" integer,
	"attrWifiTxLinkSpeedMbps" integer,
	"attrWifiMaxSupportedRxLinkSpeedMbps" integer,
	"attrWifiMaxSupportedTxLinkSpeedMbps" integer,
	"attrWifiStandard" text,
	"idWifiStandard" smallint,
	"valDownloadMbps" double precision,
	"valUploadMbps" double precision,
	"numTestDownloadThreads" smallint,
	"numTestUploadThreads" smallint,
	"valLatencyMinMs" integer,
	"valLatencyIqmMs" double precision,
	"valLatencyMaxMs" integer,
	"valMultiserverLatencyMs" double precision,
	"valDownloadLatencyMinMs" double precision,
	"valDownloadLatencyIqmMs" double precision,
	"valDownloadLatencyMaxMs" double precision,
	"valUploadLatencyMinMs" double precision,
	"valUploadLatencyIqmMs" double precision,
	"valUploadLatencyMaxMs" double precision,
	"valJitterMs" integer,
	"valMultiserverJitterMs" double precision,
	"numPacketLossSent" integer,
	"numPacketLossReceived" integer,
	"metricPacketLossPercent" double precision,
	"numTracerouteHops" smallint,
	"attrTraceroute0IpAddress" text,
	"valTraceroute0LatencyMs" integer,
	"attrTraceroute0PingMtu" integer,
	"attrTraceroute1IpAddress" text,
	"valTraceroute1LatencyMs" integer,
	"attrTraceroute1PingMtu" integer,
	"attrNetworkIpv4Address" text,
	"attrNetworkIpv6Address" text,
	"attrNetworkAsn" bigint,
	"isNetworkVpn" boolean,
	"attrAppVersion" text,
	"attrServerName" text,
	"attrServerSponsorName" text,
	"attrServerLatitude" double precision,
	"attrServerLongitude" double precision,
	"attrServerDistanceKm" integer,
	"attrServerCountryCode" text,
	"isServerAutoSelected" boolean,
	"isServerOnNetwork" boolean,
	"attrServerAsn" bigint,
	"numServerDownload" smallint,
	"attrSignalCellType" smallint,
	"attrCellFrequencyChannel" integer,
	"attrCellFrequencyChannelType" text,
	"attrCellLac" integer,
	"attrCellNrPci" smallint,
	"isPortalIncluded" boolean,
	"attrPortalCategories" text,
	"valAsuLevel" integer,
	"valNrAsuLevel" integer,
	"isAppPermissionPhoneState" boolean,
	"isAppPermissionFineLocation" boolean,
	"isAppPermissionCoarseLocation" boolean,
	"isAppPermissionBackgroundLocation" boolean,
	"isAppPermissionWifiState" boolean,
	"ingestedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "networkPerformanceFixed_idResult_tsResult_pk" PRIMARY KEY("idResult","tsResult")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "networkPerformanceMobile" (
	"idResult" bigint NOT NULL,
	"guidResult" text,
	"idPlatform" smallint,
	"tsResult" timestamp with time zone NOT NULL,
	"tsResultReceived" timestamp with time zone,
	"attrLocationTimezone" text,
	"idDevice" integer,
	"attrDeviceAndroidFingerprint" text,
	"attrDeviceModel" text,
	"attrDeviceManufacturer" text,
	"attrDeviceModelRaw" text,
	"attrDeviceManufacturerRaw" text,
	"attrDeviceBrandRaw" text,
	"attrDeviceChipset" text,
	"attrDeviceChipsetManufacturer" text,
	"attrDeviceHardwareName" text,
	"attrDeviceOsVersion" text,
	"attrDeviceBuild" text,
	"isDeviceRooted" boolean,
	"attrDeviceRadio" text,
	"attrDeviceRamMb" integer,
	"attrDeviceStorageMb" integer,
	"isDeviceWorldPhone" boolean,
	"attrDeviceMultiSimSupport" smallint,
	"numDeviceActiveModems" integer,
	"numDeviceSupportedModems" integer,
	"isDeviceConcurrentVoiceDataSupported" boolean,
	"isDeviceDataConnectionAllowed" boolean,
	"isDeviceDataCapable" boolean,
	"isDeviceDataRoamingEnabled" boolean,
	"isDeviceIccCardPresent" boolean,
	"attrDeviceServiceState" smallint,
	"attrDeviceThermalStatus" integer,
	"valDeviceThermalHeadroom" double precision,
	"attrDeviceSoftwareVersion" text,
	"attrDeviceEsimEmbedded" boolean,
	"isAppPermissionPhoneState" boolean,
	"isAppPermissionFineLocation" boolean,
	"isAppPermissionCoarseLocation" boolean,
	"isAppPermissionBackgroundLocation" boolean,
	"isAppPermissionWifiState" boolean,
	"attrSimOperatorCommonName" text,
	"attrSimOperatorNameRaw" text,
	"attrSimOperatorMcc" integer,
	"attrSimOperatorMnc" integer,
	"attrAltsimOperatorName" text,
	"attrAltsimOperatorMcc" integer,
	"attrAltsimOperatorMnc" integer,
	"attrNetworkOperatorMcc" integer,
	"attrNetworkOperatorMnc" integer,
	"attrNetworkOperatorCommonName" text,
	"attrIspCommonName" text,
	"attrIspNameRaw" text,
	"attrSimTypeAllocationCode" text,
	"attrSimState" smallint,
	"attrTestMethod" text,
	"attrTestIpVersion" smallint,
	"idConnectionTypeStart" smallint,
	"idConnectionTypeEnd" smallint,
	"numConnectionsFailed" smallint,
	"isConnectionCarrierAggregation" text,
	"attrConnectionNrState" integer,
	"attrConnectionApn" text,
	"idConnectionNetSpeed" integer,
	"isConnectionAccessTechnologyNr" boolean,
	"idConnectionNetworkOverrideType" smallint,
	"attrConnectionDownstreamBandwidthKbps" integer,
	"attrConnectionUpstreamBandwidthKbps" integer,
	"attrConnectionNat64Prefix" text,
	"attrConnectionTypeStartString" text,
	"attrConnectionTypeEndString" text,
	"attrLocationLatitude" double precision,
	"attrLocationLongitude" double precision,
	"attrLocationStartLatitude" double precision,
	"attrLocationStartLongitude" double precision,
	"idLocationStartType" smallint,
	"idLocationEndType" smallint,
	"attrLocationAccuracyM" integer,
	"attrLocationAgeMs" bigint,
	"attrLocationAltitudeM" integer,
	"attrLocationVerticalAccuracyM" integer,
	"attrLocationSpeedMps" double precision,
	"attrPlaceFormattedAddress" text,
	"attrPlaceName" text,
	"attrPlaceLocalityType" text,
	"attrPlaceCountry" text,
	"attrPlaceCountryCode" text,
	"attrPlaceRegion" text,
	"attrPlaceSubregion" text,
	"attrPlaceSubsubregion" text,
	"attrPlacePostalCode" text,
	"valDownloadKbps" integer,
	"valUploadKbps" integer,
	"valTestDownloadKb" integer,
	"numTestDownloadThreads" smallint,
	"valTestDownloadDurationMs" integer,
	"valTestUploadKb" integer,
	"numTestUploadThreads" smallint,
	"valTestUploadDurationMs" integer,
	"isDownloadStopped" boolean,
	"valLatencyMinMs" integer,
	"valLatencyIqmMs" double precision,
	"valLatencyMaxMs" integer,
	"valMultiserverLatencyMs" double precision,
	"valDownloadLatencyMinMs" double precision,
	"valDownloadLatencyIqmMs" double precision,
	"valDownloadLatencyMaxMs" double precision,
	"valUploadLatencyMinMs" double precision,
	"valUploadLatencyIqmMs" double precision,
	"valUploadLatencyMaxMs" double precision,
	"valJitterMs" double precision,
	"valMultiserverJitterMs" double precision,
	"numPacketLossSent" integer,
	"numPacketLossReceived" integer,
	"metricPacketLossPercent" double precision,
	"numTracerouteHops" smallint,
	"attrTraceroute0IpAddress" text,
	"valTraceroute0LatencyMs" integer,
	"attrTraceroute0PingMtu" integer,
	"attrTraceroute1IpAddress" text,
	"valTraceroute1LatencyMs" integer,
	"attrTraceroute1PingMtu" integer,
	"attrNetworkIpv4Address" text,
	"attrNetworkIpv6Address" text,
	"attrNetworkAsn" bigint,
	"isNetworkRoaming" boolean,
	"isNetworkInternationalRoaming" boolean,
	"isNetworkVpn" boolean,
	"isDevice5gCapable" boolean,
	"attrAppVersion" text,
	"attrAppStore" text,
	"attrServerName" text,
	"attrServerSponsorName" text,
	"attrServerLatitude" double precision,
	"attrServerLongitude" double precision,
	"valServerDistanceKm" integer,
	"attrServerCountry" text,
	"attrServerCountryCode" text,
	"isServerAutoSelected" boolean,
	"isServerOnNetwork" boolean,
	"attrServerAsn" bigint,
	"numServerDownload" smallint,
	"valSignalRsrpDbm" bigint,
	"valSignalCsiRsrpDbm" smallint,
	"valSignalSsRsrpDbm" smallint,
	"valSignalRsrqDb" smallint,
	"valSignalCsiRsrqDb" smallint,
	"valSignalSsRsrqDb" smallint,
	"valSignalRssnrDb" smallint,
	"valSignalCsiSnrDb" smallint,
	"valSignalSsSnrDb" smallint,
	"valSignalWcdmaEcnoDb" integer,
	"valSignalRssiDbm" integer,
	"valSignalGsmRssiDbm" integer,
	"valSignalTimingAdvanceTs" integer,
	"valSignalCqi" smallint,
	"attrSignalCellType" smallint,
	"attrCellNrFrequencyRange" smallint,
	"attrCellBandwidthKhz" integer,
	"attrCellBandwidthsKhz" text,
	"idCellPrimary" bigint,
	"idCellLteEnodeb" bigint,
	"attrCellPci" integer,
	"attrCellNrPci" smallint,
	"attrCellTac" integer,
	"attrCellLac" integer,
	"attrCellPsc" integer,
	"attrCellFrequencyChannel" integer,
	"attrCellFrequencyChannelType" text,
	"attrCellNrArfcn" integer,
	"attrCellLteBands" text,
	"attrCellNrBands" text,
	"idCellNr" bigint,
	"idCellStart" integer,
	"idCellGsm" bigint,
	"attrNetworkOperatorMccNr" text,
	"attrNetworkOperatorMncNr" text,
	"idLocationBuilding" text,
	"valIndoorConfidenceLevel" real,
	"isPortalIncluded" boolean,
	"attrPortalCategories" text,
	"valAsuLevel" integer,
	"valNrAsuLevel" integer,
	"ingestedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "networkPerformanceMobile_idResult_tsResult_pk" PRIMARY KEY("idResult","tsResult")
);
--> statement-breakpoint
ALTER TABLE "file_transfer" ALTER COLUMN "attr_private_ip_address" SET DATA TYPE inet[] USING "attr_private_ip_address"::inet[];--> statement-breakpoint
ALTER TABLE "file_transfer" ALTER COLUMN "attr_network_ipv4_address" SET DATA TYPE inet USING "attr_network_ipv4_address"::inet;--> statement-breakpoint
ALTER TABLE "file_transfer" ALTER COLUMN "attr_network_ipv6_address" SET DATA TYPE inet USING "attr_network_ipv6_address"::inet;--> statement-breakpoint
ALTER TABLE "file_transfer" ALTER COLUMN "attr_server_ipv4_address" SET DATA TYPE inet USING "attr_server_ipv4_address"::inet;--> statement-breakpoint
ALTER TABLE "video" ALTER COLUMN "attr_private_ip_address" SET DATA TYPE inet[] USING "attr_private_ip_address"::inet[];--> statement-breakpoint
ALTER TABLE "video" ALTER COLUMN "attr_network_ipv6_address" SET DATA TYPE inet USING "attr_network_ipv6_address"::inet;--> statement-breakpoint
ALTER TABLE "video" ALTER COLUMN "attr_server_ipv4_address" SET DATA TYPE inet USING "attr_server_ipv4_address"::inet;--> statement-breakpoint
ALTER TABLE "video" ALTER COLUMN "attr_gateway_ip_address" SET DATA TYPE inet USING "attr_gateway_ip_address"::inet;--> statement-breakpoint
ALTER TABLE "web_browsing" ALTER COLUMN "attr_private_ip_address" SET DATA TYPE inet[] USING "attr_private_ip_address"::inet[];--> statement-breakpoint
ALTER TABLE "web_browsing" ALTER COLUMN "attr_network_ipv4_address" SET DATA TYPE inet USING "attr_network_ipv4_address"::inet;--> statement-breakpoint
ALTER TABLE "web_browsing" ALTER COLUMN "attr_network_ipv6_address" SET DATA TYPE inet USING "attr_network_ipv6_address"::inet;