-- =============================================================================
-- Migration 0026: qoe_latency (Ookla ConsumerQoE/QoELatency)
--
-- Schema derivado do header real do parquet (138 colunas), capturado via
-- `python -m ookla_ingest sniff --entity QoELatency` em data-core/ookla/.
-- Convencao snake_case alinhada com as outras tabelas QoE (file_transfer,
-- video, web_browsing). Hypertable em ts_result. Listas (parquet list<>)
-- sao serializadas como JSON em colunas text pelo loader.
-- =============================================================================

CREATE TABLE IF NOT EXISTS qoe_latency (
    guid_result                                  text,
    id_device                                    text,
    id_platform                                  integer,
    attr_latency_type                            text,
    attr_service_name                            text,
    ts_result                                    timestamptz NOT NULL,
    ts_result_received                           timestamptz,
    attr_device_model_raw                        text,
    attr_device_brand_raw                        text,
    attr_device_os_version                       integer,
    num_device_sim_slots                         integer,
    id_device_sim_slot                           integer,
    attr_sim_operator_mcc                        text,
    attr_altsim_operator_mcc                     text,
    attr_sim_operator_mnc                        text,
    attr_altsim_operator_mnc                     text,
    attr_sim_operator_name_raw                   text,
    attr_altsim_operator_name_raw                text,
    attr_network_operator_mcc                    text,
    attr_network_operator_mnc                    text,
    attr_network_operator_name_raw               text,
    attr_network_asn                             integer,
    num_connections_failed                       integer,
    is_connection_carrier_aggregation            boolean,
    attr_connection_nr_state                     text,
    id_connection_network_override_type          integer,
    attr_connection_downstream_bandwidth_kbps    integer,
    attr_connection_upstream_bandwidth_kbps      integer,
    attr_vops_support                            integer,
    attr_location_latitude                       numeric(10, 5),
    attr_location_longitude                      numeric(10, 5),
    attr_location_accuracy_m                     real,
    attr_location_age_ms                         integer,
    attr_location_altitude_m                     double precision,
    attr_location_vertical_accuracy_m            real,
    attr_location_speed_mps                      double precision,
    attr_location_speed_accuracy_mps             double precision,
    val_latency_ms                               real,
    val_jitter_ms                                real,
    attr_network_ipv4_address                    text,
    attr_network_ipv6_address                    text,
    attr_data_source_version                     text,
    attr_server_name                             text,
    attr_server_ipv4_address                     text,
    attr_server_ipv6_address                     text,
    attr_server_url                              text,
    is_device_rooted                             boolean,
    is_network_vpn                               boolean,
    val_signal_rsrp_dbm                          integer,
    val_signal_csi_rsrp_dbm                      integer,
    val_signal_ss_rsrp_dbm                       integer,
    val_signal_rsrq_db                           integer,
    val_signal_csi_rsrq_db                       integer,
    val_signal_ss_rsrq_db                        integer,
    val_signal_rssnr_db                          integer,
    val_signal_csi_snr_db                        integer,
    val_signal_ss_snr_db                         integer,
    val_signal_asu                               integer,
    val_signal_timing_advance_ts                 integer,
    val_signal_cqi                               integer,
    id_cell_primary                              bigint,
    attr_cell_pci                                integer,
    attr_cell_lac                                integer,
    attr_cell_frequency_channel                  integer,
    attr_cell_frequency_channel_type             text,
    attr_cell_nr_frequency_range                 integer,
    attr_cell_bands                              text,
    attr_cell_bandwidths_khz                     text,
    attr_location_timezone                       text,
    attr_device_model                            text,
    attr_sim_operator_common_name                text,
    attr_network_operator_common_name            text,
    attr_network_isp_name                        text,
    attr_network_isp_common_name                 text,
    attr_connection_tech_name                    text,
    attr_connection_standard_name                text,
    attr_connection_family_name                  text,
    attr_connection_family_name_first_hop        text,
    attr_connection_generation_name              text,
    attr_place_formatted_address                 text,
    attr_place_name                              text,
    attr_place_locality_type                     text,
    attr_place_country                           text,
    attr_place_country_code                      text,
    attr_place_region                            text,
    attr_place_subregion                         text,
    attr_place_subsubregion                      text,
    attr_place_postal_code                       text,
    is_network_international_roaming             boolean,
    is_carrier_resolved_from_ip_address          boolean,
    attr_wifi_frequency_mhz                      integer,
    attr_wifi_channel_width_id                   integer,
    attr_wifi_standard                           text,
    id_wifi_standard                             integer,
    attr_wifi_rssi_dbm                           integer,
    attr_wifi_max_supported_rx_link_speed_mbps   integer,
    attr_wifi_max_supported_tx_link_speed_mbps   integer,
    attr_wifi_rx_link_speed_mbps                 integer,
    attr_wifi_tx_link_speed_mbps                 integer,
    is_wifi_connected                            boolean,
    val_packet_loss_ratio                        double precision,
    num_connections_attempted                    integer,
    id_location_building                         text,
    val_indoor_confidence_level                  real,
    attr_device_battery_state                    integer,
    val_device_battery_temperature               real,
    val_device_cpu_usage                         real,
    val_device_ram                               integer,
    val_device_free_ram                          integer,
    val_device_maximum_storage                   integer,
    val_device_free_storage                      integer,
    is_device_5g_capable                         boolean,
    attr_connection_type                         integer,
    attr_cell_technology_standard_name           text,
    attr_geohash6                                text,
    attr_geohash7                                text,
    attr_geohash8                                text,
    id_location_type                             integer,
    attr_private_ip_address                      text,
    attr_cell_tac                                integer,
    is_dc_nr_restricted                          boolean,
    is_en_dc_available                           boolean,
    is_cell_nr_available                         boolean,
    is_cell_network_registered                   boolean,
    val_signal_ecno                              integer,
    val_signal_rssi_dbm                          integer,
    attr_signal_rscp                             integer,
    val_network_bsic_code                        integer,
    attr_radio_access_technology_type_name       text,
    id_device_vops_support                       integer,
    attr_network_wcdma_additional_plmns          text,
    attr_network_lte_additional_plmns            text,
    attr_network_nr_additional_plmns             text,
    attr_cell_nr_arfcn                           integer,
    attr_cell_nr_pci                             integer,
    attr_sim_type_allocation_code                text,
    attr_cell_secondary_arfcn                    integer,
    id_connection_net_speed                      integer
);--> statement-breakpoint

SELECT create_hypertable('qoe_latency', by_range('ts_result'), if_not_exists => TRUE);--> statement-breakpoint

-- Unique index para suportar ON CONFLICT na carga via copy_loader.
-- guid_result pode ser NULL — duplicates com NULL serao aceitos (raro).
-- A coluna de tempo (ts_result) e obrigatoria em hypertables p/ unique indexes.
CREATE UNIQUE INDEX IF NOT EXISTS qoe_latency_guid_ts_uniq
    ON qoe_latency (guid_result, ts_result);--> statement-breakpoint

CREATE INDEX IF NOT EXISTS idx_qoe_latency_geohash7
    ON qoe_latency (attr_geohash7, ts_result DESC);--> statement-breakpoint

CREATE INDEX IF NOT EXISTS idx_qoe_latency_geohash6
    ON qoe_latency (attr_geohash6, ts_result DESC);--> statement-breakpoint

CREATE INDEX IF NOT EXISTS idx_qoe_latency_operator_month
    ON qoe_latency (attr_sim_operator_common_name, DATE_TRUNC('month', ts_result AT TIME ZONE 'UTC'));
