import {
  pgTable,
  text,
  integer,
  bigint,
  numeric,
  doublePrecision,
  real,
  boolean,
  timestamp,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";

// Schema derivado do header parquet (138 colunas) — capturado via
// `python -m ookla_ingest sniff --entity QoELatency`.
// Convencao snake_case (mesma das outras 3 tabelas QoE).
// Listas (parquet list<int>/list<string>) sao serializadas como JSON em text.
export const qoeLatency = pgTable(
  "qoe_latency",
  {
    guidResult: text("guid_result"),
    idDevice: text("id_device"),
    idPlatform: integer("id_platform"),
    attrLatencyType: text("attr_latency_type"),
    attrServiceName: text("attr_service_name"),
    tsResult: timestamp("ts_result", {
      withTimezone: true,
      mode: "string",
    }).notNull(),
    tsResultReceived: timestamp("ts_result_received", {
      withTimezone: true,
      mode: "string",
    }),
    attrDeviceModelRaw: text("attr_device_model_raw"),
    attrDeviceBrandRaw: text("attr_device_brand_raw"),
    attrDeviceOsVersion: integer("attr_device_os_version"),
    numDeviceSimSlots: integer("num_device_sim_slots"),
    idDeviceSimSlot: integer("id_device_sim_slot"),
    attrSimOperatorMcc: text("attr_sim_operator_mcc"),
    attrAltsimOperatorMcc: text("attr_altsim_operator_mcc"),
    attrSimOperatorMnc: text("attr_sim_operator_mnc"),
    attrAltsimOperatorMnc: text("attr_altsim_operator_mnc"),
    attrSimOperatorNameRaw: text("attr_sim_operator_name_raw"),
    attrAltsimOperatorNameRaw: text("attr_altsim_operator_name_raw"),
    attrNetworkOperatorMcc: text("attr_network_operator_mcc"),
    attrNetworkOperatorMnc: text("attr_network_operator_mnc"),
    attrNetworkOperatorNameRaw: text("attr_network_operator_name_raw"),
    attrNetworkAsn: integer("attr_network_asn"),
    numConnectionsFailed: integer("num_connections_failed"),
    isConnectionCarrierAggregation: boolean("is_connection_carrier_aggregation"),
    attrConnectionNrState: text("attr_connection_nr_state"),
    idConnectionNetworkOverrideType: integer("id_connection_network_override_type"),
    attrConnectionDownstreamBandwidthKbps: integer(
      "attr_connection_downstream_bandwidth_kbps"
    ),
    attrConnectionUpstreamBandwidthKbps: integer(
      "attr_connection_upstream_bandwidth_kbps"
    ),
    attrVopsSupport: integer("attr_vops_support"),
    attrLocationLatitude: numeric("attr_location_latitude", {
      precision: 10,
      scale: 5,
    }),
    attrLocationLongitude: numeric("attr_location_longitude", {
      precision: 10,
      scale: 5,
    }),
    attrLocationAccuracyM: real("attr_location_accuracy_m"),
    attrLocationAgeMs: integer("attr_location_age_ms"),
    attrLocationAltitudeM: doublePrecision("attr_location_altitude_m"),
    attrLocationVerticalAccuracyM: real("attr_location_vertical_accuracy_m"),
    attrLocationSpeedMps: doublePrecision("attr_location_speed_mps"),
    attrLocationSpeedAccuracyMps: doublePrecision(
      "attr_location_speed_accuracy_mps"
    ),
    valLatencyMs: real("val_latency_ms"),
    valJitterMs: real("val_jitter_ms"),
    attrNetworkIpv4Address: text("attr_network_ipv4_address"),
    attrNetworkIpv6Address: text("attr_network_ipv6_address"),
    attrDataSourceVersion: text("attr_data_source_version"),
    attrServerName: text("attr_server_name"),
    attrServerIpv4Address: text("attr_server_ipv4_address"),
    attrServerIpv6Address: text("attr_server_ipv6_address"),
    attrServerUrl: text("attr_server_url"),
    isDeviceRooted: boolean("is_device_rooted"),
    isNetworkVpn: boolean("is_network_vpn"),
    valSignalRsrpDbm: integer("val_signal_rsrp_dbm"),
    valSignalCsiRsrpDbm: integer("val_signal_csi_rsrp_dbm"),
    valSignalSsRsrpDbm: integer("val_signal_ss_rsrp_dbm"),
    valSignalRsrqDb: integer("val_signal_rsrq_db"),
    valSignalCsiRsrqDb: integer("val_signal_csi_rsrq_db"),
    valSignalSsRsrqDb: integer("val_signal_ss_rsrq_db"),
    valSignalRssnrDb: integer("val_signal_rssnr_db"),
    valSignalCsiSnrDb: integer("val_signal_csi_snr_db"),
    valSignalSsSnrDb: integer("val_signal_ss_snr_db"),
    valSignalAsu: integer("val_signal_asu"),
    valSignalTimingAdvanceTs: integer("val_signal_timing_advance_ts"),
    valSignalCqi: integer("val_signal_cqi"),
    idCellPrimary: bigint("id_cell_primary", { mode: "number" }),
    attrCellPci: integer("attr_cell_pci"),
    attrCellLac: integer("attr_cell_lac"),
    attrCellFrequencyChannel: integer("attr_cell_frequency_channel"),
    attrCellFrequencyChannelType: text("attr_cell_frequency_channel_type"),
    attrCellNrFrequencyRange: integer("attr_cell_nr_frequency_range"),
    attrCellBands: text("attr_cell_bands"),
    attrCellBandwidthsKhz: text("attr_cell_bandwidths_khz"),
    attrLocationTimezone: text("attr_location_timezone"),
    attrDeviceModel: text("attr_device_model"),
    attrSimOperatorCommonName: text("attr_sim_operator_common_name"),
    attrNetworkOperatorCommonName: text("attr_network_operator_common_name"),
    attrNetworkIspName: text("attr_network_isp_name"),
    attrNetworkIspCommonName: text("attr_network_isp_common_name"),
    attrConnectionTechName: text("attr_connection_tech_name"),
    attrConnectionStandardName: text("attr_connection_standard_name"),
    attrConnectionFamilyName: text("attr_connection_family_name"),
    attrConnectionFamilyNameFirstHop: text("attr_connection_family_name_first_hop"),
    attrConnectionGenerationName: text("attr_connection_generation_name"),
    attrPlaceFormattedAddress: text("attr_place_formatted_address"),
    attrPlaceName: text("attr_place_name"),
    attrPlaceLocalityType: text("attr_place_locality_type"),
    attrPlaceCountry: text("attr_place_country"),
    attrPlaceCountryCode: text("attr_place_country_code"),
    attrPlaceRegion: text("attr_place_region"),
    attrPlaceSubregion: text("attr_place_subregion"),
    attrPlaceSubsubregion: text("attr_place_subsubregion"),
    attrPlacePostalCode: text("attr_place_postal_code"),
    isNetworkInternationalRoaming: boolean("is_network_international_roaming"),
    isCarrierResolvedFromIpAddress: boolean("is_carrier_resolved_from_ip_address"),
    attrWifiFrequencyMhz: integer("attr_wifi_frequency_mhz"),
    attrWifiChannelWidthId: integer("attr_wifi_channel_width_id"),
    attrWifiStandard: text("attr_wifi_standard"),
    idWifiStandard: integer("id_wifi_standard"),
    attrWifiRssiDbm: integer("attr_wifi_rssi_dbm"),
    attrWifiMaxSupportedRxLinkSpeedMbps: integer(
      "attr_wifi_max_supported_rx_link_speed_mbps"
    ),
    attrWifiMaxSupportedTxLinkSpeedMbps: integer(
      "attr_wifi_max_supported_tx_link_speed_mbps"
    ),
    attrWifiRxLinkSpeedMbps: integer("attr_wifi_rx_link_speed_mbps"),
    attrWifiTxLinkSpeedMbps: integer("attr_wifi_tx_link_speed_mbps"),
    isWifiConnected: boolean("is_wifi_connected"),
    valPacketLossRatio: doublePrecision("val_packet_loss_ratio"),
    numConnectionsAttempted: integer("num_connections_attempted"),
    idLocationBuilding: text("id_location_building"),
    valIndoorConfidenceLevel: real("val_indoor_confidence_level"),
    attrDeviceBatteryState: integer("attr_device_battery_state"),
    valDeviceBatteryTemperature: real("val_device_battery_temperature"),
    valDeviceCpuUsage: real("val_device_cpu_usage"),
    valDeviceRam: integer("val_device_ram"),
    valDeviceFreeRam: integer("val_device_free_ram"),
    valDeviceMaximumStorage: integer("val_device_maximum_storage"),
    valDeviceFreeStorage: integer("val_device_free_storage"),
    isDevice5gCapable: boolean("is_device_5g_capable"),
    attrConnectionType: integer("attr_connection_type"),
    attrCellTechnologyStandardName: text("attr_cell_technology_standard_name"),
    attrGeohash6: text("attr_geohash6"),
    attrGeohash7: text("attr_geohash7"),
    attrGeohash8: text("attr_geohash8"),
    idLocationType: integer("id_location_type"),
    attrPrivateIpAddress: text("attr_private_ip_address"),
    attrCellTac: integer("attr_cell_tac"),
    isDcNrRestricted: boolean("is_dc_nr_restricted"),
    isEnDcAvailable: boolean("is_en_dc_available"),
    isCellNrAvailable: boolean("is_cell_nr_available"),
    isCellNetworkRegistered: boolean("is_cell_network_registered"),
    valSignalEcno: integer("val_signal_ecno"),
    valSignalRssiDbm: integer("val_signal_rssi_dbm"),
    attrSignalRscp: integer("attr_signal_rscp"),
    valNetworkBsicCode: integer("val_network_bsic_code"),
    attrRadioAccessTechnologyTypeName: text("attr_radio_access_technology_type_name"),
    idDeviceVopsSupport: integer("id_device_vops_support"),
    attrNetworkWcdmaAdditionalPlmns: text("attr_network_wcdma_additional_plmns"),
    attrNetworkLteAdditionalPlmns: text("attr_network_lte_additional_plmns"),
    attrNetworkNrAdditionalPlmns: text("attr_network_nr_additional_plmns"),
    attrCellNrArfcn: integer("attr_cell_nr_arfcn"),
    attrCellNrPci: integer("attr_cell_nr_pci"),
    attrSimTypeAllocationCode: text("attr_sim_type_allocation_code"),
    attrCellSecondaryArfcn: integer("attr_cell_secondary_arfcn"),
    idConnectionNetSpeed: integer("id_connection_net_speed"),
  },
  (t) => ({
    guidTsUniq: uniqueIndex("qoe_latency_guid_ts_uniq").on(t.guidResult, t.tsResult),
    geohash7Idx: index("idx_qoe_latency_geohash7").on(t.attrGeohash7, t.tsResult),
    geohash6Idx: index("idx_qoe_latency_geohash6").on(t.attrGeohash6, t.tsResult),
  })
);
