CREATE TYPE "public"."benchmark_scope" AS ENUM('NACIONAL', 'ESTADO', 'CIDADE');--> statement-breakpoint
CREATE TYPE "public"."competitive_position" AS ENUM('LIDER', 'COMPETITIVO', 'EMPAREDADA', 'ABAIXO', 'ISOLADA');--> statement-breakpoint
CREATE TYPE "public"."fibra_class" AS ENUM('AUMENTO_CAPACIDADE', 'EXPANSAO_NOVA_AREA', 'SAUDAVEL');--> statement-breakpoint
CREATE TYPE "public"."movel_class" AS ENUM('MELHORA_QUALIDADE', 'SAUDAVEL', 'EXPANSAO_COBERTURA');--> statement-breakpoint
CREATE TYPE "public"."operator_name" AS ENUM('VIVO', 'TIM', 'CLARO', 'OI', 'OUTROS');--> statement-breakpoint
CREATE TYPE "public"."priority_label" AS ENUM('P1_CRITICA', 'P2_ALTA', 'P3_MEDIA', 'P4_BAIXA');--> statement-breakpoint
CREATE TYPE "public"."quadrant_type" AS ENUM('OPORTUNIDADE', 'FORTALEZA', 'EXPANSAO', 'RISCO');--> statement-breakpoint
CREATE TYPE "public"."quality_label" AS ENUM('EXCELENTE', 'BOM', 'REGULAR', 'RUIM');--> statement-breakpoint
CREATE TYPE "public"."share_level" AS ENUM('MUITO_ALTA', 'ALTA', 'MEDIA', 'BAIXA');--> statement-breakpoint
CREATE TYPE "public"."tech_category" AS ENUM('FIBRA', 'MOVEL', 'AMBOS');--> statement-breakpoint
CREATE TYPE "public"."trend_direction" AS ENUM('UP', 'DOWN', 'STABLE');--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "file_transfer" (
	"ts_result" timestamp with time zone NOT NULL,
	"ts_result_received" timestamp with time zone,
	"id_platform" varchar(7),
	"id_device" varchar(35),
	"guid_result" text,
	"attr_location_timezone" varchar(50),
	"has_ul_test_status" boolean,
	"val_ul_throughput" double precision,
	"val_ul_file_size" integer,
	"has_dl_test_status" boolean,
	"val_dl_throughput" double precision,
	"val_dl_file_size" integer,
	"has_latency_test_status" boolean,
	"val_latency_avg" integer,
	"attr_device_model_raw" varchar(255),
	"attr_device_model" varchar(255),
	"attr_device_brand_raw" varchar(255),
	"attr_device_os_version" varchar(20),
	"id_device_sim_slot" smallint,
	"num_device_sim_slots" smallint,
	"attr_device_battery_state" varchar(2),
	"val_device_battery_temperature" real,
	"val_device_cpu_usage" real,
	"val_device_ram" bigint,
	"val_device_free_ram" bigint,
	"val_device_maximum_storage" bigint,
	"val_device_free_storage" bigint,
	"is_device_5g_capable" boolean,
	"attr_sim_operator_common_name" varchar(255),
	"attr_sim_operator_mcc" smallint,
	"attr_sim_operator_mnc" smallint,
	"attr_network_operator_mcc" smallint,
	"attr_network_operator_mnc" smallint,
	"attr_sim_operator_name_raw" varchar(255),
	"attr_altsim_operator_mcc" varchar(3),
	"attr_altsim_operator_mnc" varchar(3),
	"attr_altsim_operator_name_raw" varchar(255),
	"attr_network_operator_name_raw" varchar(255),
	"attr_network_isp_name" varchar(255),
	"attr_network_asn" bigint,
	"attr_connection_tech_name" varchar(255),
	"attr_connection_standard_name" varchar(255),
	"attr_connection_family_name" varchar(255),
	"attr_connection_family_name_first_hop" varchar(255),
	"attr_connection_generation_name" varchar(255),
	"attr_connection_downstream_bandwidth_kbps" integer,
	"attr_connection_upstream_bandwidth_kbps" integer,
	"attr_vops_support" smallint,
	"is_connection_carrier_aggregation" boolean,
	"attr_connection_nr_state" varchar(1),
	"id_connection_network_override_type" real,
	"attr_network_operator_name" varchar(255),
	"attr_dl_access_tech_end" varchar(14),
	"val_dl_access_tech_num_changes" smallint,
	"attr_dl_access_tech_start" varchar(14),
	"val_dl_first_byte_time" integer,
	"attr_ul_access_tech_end" varchar(14),
	"val_ul_access_tech_num_changes" smallint,
	"attr_ul_access_tech_start" varchar(14),
	"val_ul_first_byte_time" integer,
	"val_dns_lookup_time" integer,
	"val_tcp_connect_time" integer,
	"val_tls_setup_time" integer,
	"attr_endpoint_type" varchar(10),
	"is_network_roaming" boolean,
	"is_network_vpn" boolean,
	"attr_location_latitude" double precision,
	"attr_location_longitude" double precision,
	"attr_location_accuracy_m" real,
	"attr_location_age_ms" integer,
	"attr_location_speed_mps" double precision,
	"attr_location_speed_accuracy_mps" double precision,
	"attr_place_formatted_address" varchar(100),
	"attr_place_name" varchar(100),
	"attr_place_locality_type" varchar(100),
	"attr_place_country" varchar(100),
	"attr_place_country_code" varchar(2),
	"attr_place_region" varchar(100),
	"attr_place_subregion" varchar(100),
	"attr_place_subsubregion" varchar(100),
	"attr_place_postal_code" varchar(100),
	"attr_geohash6" varchar(6),
	"attr_geohash7" varchar(7),
	"attr_geohash8" varchar(8),
	"attr_location_altitude_m" double precision,
	"attr_location_vertical_accuracy_m" double precision,
	"id_location_type" smallint,
	"val_bytes_received" bigint,
	"val_bytes_sent" bigint,
	"attr_private_ip_address" text,
	"attr_network_ipv4_address" text,
	"attr_network_ipv6_address" text,
	"attr_data_source_version" varchar(20),
	"attr_server_ipv4_address" text,
	"attr_server_name" varchar(100),
	"val_signal_cqi" integer,
	"val_signal_rsrp_dbm" integer,
	"val_signal_rsrq_db" integer,
	"val_signal_rsrp_dbm2" integer,
	"val_signal_rssnr_db" integer,
	"val_signal_timing_advance_ts" integer,
	"val_signal_csi_snr_db" integer,
	"val_signal_csi_rsrp_dbm" integer,
	"val_signal_csi_rsrq_db" integer,
	"val_signal_ss_snr_db" integer,
	"val_signal_ss_rsrp_dbm" integer,
	"val_signal_ss_rsrq_db" integer,
	"attr_cell_bandwidths_khz" varchar(100),
	"id_cell_primary" bigint,
	"attr_cell_arfcn" bigint,
	"attr_cell_pci" integer,
	"attr_cell_lac" bigint,
	"attr_cell_tac" bigint,
	"is_cell_nr_available" boolean,
	"attr_cell_nr_frequency_range" integer,
	"id_cell_lte_enodeb" bigint,
	"attr_cell_bands" text,
	"attr_cell_frequency_channel" bigint,
	"attr_cell_frequency_channel_type" varchar(10),
	"attr_wifi_frequency_mhz" integer,
	"attr_wifi_channel_width_mhz" smallint,
	"attr_wifi_standard" varchar(25),
	"id_wifi_standard" smallint,
	"attr_wifi_rssi_dbm" integer,
	"attr_wifi_max_supported_rx_link_speed_mbps" integer,
	"attr_wifi_max_supported_tx_link_speed_mbps" integer,
	"attr_wifi_rx_link_speed_mbps" integer,
	"attr_wifi_tx_link_speed_mbps" integer,
	"is_wifi_connected" boolean,
	"id_location_building" varchar(255),
	"val_indoor_confidence_level" real,
	"dt_foto" date
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "video" (
	"ts_result" timestamp with time zone NOT NULL,
	"ts_result_received" timestamp with time zone,
	"id_platform" varchar(7),
	"id_device" varchar(35),
	"guid_result" text,
	"attr_location_timezone" varchar(50),
	"val_video_time_to_start" integer,
	"attr_video_initial_buffering_time" integer,
	"attr_video_rebuffering_count" integer,
	"val_video_rebuffering_time" integer,
	"is_video_fails_to_start" boolean,
	"val_video_quality_time_144p" integer,
	"val_video_quality_time_240p" integer,
	"val_video_quality_time_360p" integer,
	"val_video_quality_time_480p" integer,
	"val_video_quality_time_720p" integer,
	"val_video_quality_time_1080p" integer,
	"val_video_quality_time_1440p" integer,
	"val_video_quality_time_2160p" integer,
	"attr_video_resolution" varchar(5),
	"is_video_resolution_switch_happened" boolean,
	"is_video_in_stream_failure" boolean,
	"attr_device_model_raw" varchar(255),
	"attr_device_brand_raw" varchar(255),
	"attr_device_os_version" varchar(20),
	"id_device_sim_slot" smallint,
	"num_device_sim_slots" smallint,
	"attr_device_battery_state" varchar(1),
	"val_device_battery_temperature" real,
	"val_device_cpu_usage" real,
	"val_device_ram" bigint,
	"val_device_free_ram" bigint,
	"val_device_maximum_storage" bigint,
	"val_device_free_storage" bigint,
	"is_device_5g_capable" boolean,
	"attr_sim_operator_common_name" varchar(255),
	"attr_sim_operator_mcc" smallint,
	"attr_sim_operator_mnc" smallint,
	"attr_network_operator_mcc" smallint,
	"attr_network_operator_mnc" smallint,
	"attr_sim_operator_name_raw" varchar(255),
	"attr_altsim_operator_mcc" varchar(3),
	"attr_altsim_operator_mnc" varchar(3),
	"attr_altsim_operator_name_raw" varchar(255),
	"attr_network_operator_name_raw" varchar(255),
	"attr_network_isp_name" varchar(255),
	"attr_network_asn" bigint,
	"attr_connection_tech_name" varchar(255),
	"attr_connection_downstream_bandwidth_kbps" integer,
	"attr_connection_upstream_bandwidth_kbps" integer,
	"attr_vops_support" smallint,
	"is_connection_carrier_aggregation" boolean,
	"attr_connection_nr_state" varchar(1),
	"id_connection_network_override_type" real,
	"attr_network_operator_name" varchar(100),
	"is_network_roaming" boolean,
	"attr_access_tech_end" varchar(14),
	"num_access_tech_num_changes" smallint,
	"attr_access_tech_start" varchar(14),
	"is_network_vpn" boolean,
	"attr_location_latitude" double precision,
	"attr_location_longitude" double precision,
	"attr_location_accuracy_m" real,
	"attr_location_age_ms" integer,
	"attr_location_altitude_m" double precision,
	"attr_location_speed_mps" double precision,
	"attr_location_speed_accuracy_mps" double precision,
	"attr_place_formatted_address" varchar(100),
	"attr_place_name" varchar(100),
	"attr_place_locality_type" varchar(100),
	"attr_place_country" varchar(100),
	"attr_place_country_code" varchar(2),
	"attr_place_region" varchar(100),
	"attr_place_subregion" varchar(100),
	"attr_place_subsubregion" varchar(100),
	"attr_place_postal_code" varchar(100),
	"attr_geohash6" varchar(6),
	"attr_geohash7" varchar(7),
	"attr_geohash8" varchar(8),
	"attr_location_vertical_accuracy_m" double precision,
	"id_location_type" smallint,
	"attr_private_ip_address" text,
	"attr_network_ipv6_address" text,
	"attr_data_source_version" varchar(20),
	"attr_server_ipv4_address" text,
	"attr_gateway_ip_address" text,
	"val_signal_cqi" integer,
	"val_signal_rsrp_dbm" integer,
	"val_signal_rsrq_db" integer,
	"val_signal_rsrp_dbm2" integer,
	"val_signal_rssnr_db" integer,
	"val_signal_timing_advance_ts" integer,
	"val_signal_csi_snr_db" integer,
	"val_signal_csi_rsrp_dbm" integer,
	"val_signal_csi_rsrq_db" integer,
	"val_signal_ss_snr_dbm" integer,
	"val_signal_ss_rsrp_dbm" integer,
	"val_signal_ss_rsrq_db" integer,
	"attr_cell_bandwidths_khz" varchar(100),
	"id_cell_primary" bigint,
	"attr_cell_pci" integer,
	"attr_cell_lac" bigint,
	"attr_cell_tac" bigint,
	"is_cell_service_dcnr_restricted" boolean,
	"is_cell_service_endc_available" boolean,
	"is_cell_nr_available" boolean,
	"attr_cell_nr_frequency_range" real,
	"attr_cell_bands" text,
	"attr_cell_frequency_channel" bigint,
	"attr_cell_frequency_channel_type" varchar(10),
	"attr_wifi_frequency_mhz" integer,
	"attr_wifi_channel_width_id" smallint,
	"attr_wifi_standard" varchar(25),
	"id_wifi_standard" smallint,
	"attr_wifi_rssi_dbm" integer,
	"attr_wifi_max_supported_rx_link_speed_mbps" integer,
	"attr_wifi_max_supported_tx_link_speed_mbps" integer,
	"attr_wifi_rx_link_speed_mbps" integer,
	"attr_wifi_tx_link_speed_mbps" integer,
	"is_wifi_connected" boolean,
	"id_location_building" varchar(255),
	"val_indoor_confidence_level" real,
	"dt_foto" date
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "web_browsing" (
	"ts_result" timestamp with time zone NOT NULL,
	"ts_result_received" timestamp with time zone,
	"id_platform" varchar(7),
	"id_device" varchar(35),
	"guid_result" text,
	"attr_location_timezone" varchar(50),
	"val_web_page_load_time" integer,
	"val_web_page_first_byte_time" integer,
	"is_web_page_fails_to_load" boolean,
	"attr_web_page_url" varchar(100),
	"attr_cell_bands" text,
	"attr_device_model_raw" varchar(255),
	"attr_device_brand_raw" varchar(255),
	"attr_device_os_version" varchar(20),
	"id_device_sim_slot" smallint,
	"num_device_sim_slots" smallint,
	"attr_device_battery_state" varchar(1),
	"val_device_battery_temperature" real,
	"val_device_cpu_usage" real,
	"val_device_ram" bigint,
	"val_device_free_ram" bigint,
	"val_device_maximum_storage" bigint,
	"val_device_free_storage" bigint,
	"is_device_5g_capable" boolean,
	"attr_sim_operator_common_name" varchar(255),
	"attr_sim_operator_mcc" smallint,
	"attr_sim_operator_mnc" smallint,
	"attr_network_operator_mcc" smallint,
	"attr_network_operator_mnc" smallint,
	"attr_sim_operator_name_raw" varchar(255),
	"attr_altsim_operator_mcc" varchar(3),
	"attr_altsim_operator_mnc" varchar(3),
	"attr_altsim_operator_name_raw" varchar(255),
	"attr_network_operator_name_raw" varchar(255),
	"attr_network_isp_name" varchar(255),
	"attr_network_asn" bigint,
	"attr_connection_tech_name" varchar(255),
	"attr_connection_downstream_bandwidth_kbps" integer,
	"attr_connection_upstream_bandwidth_kbps" integer,
	"attr_vops_support" smallint,
	"is_connection_carrier_aggregation" boolean,
	"attr_connection_nr_state" varchar(1),
	"id_connection_network_override_type" real,
	"attr_network_operator_name" varchar(100),
	"is_network_roaming" boolean,
	"attr_access_tech_end" varchar(14),
	"num_access_tech_num_changes" smallint,
	"attr_access_tech_start" varchar(14),
	"is_network_vpn" boolean,
	"attr_location_latitude" double precision,
	"attr_location_longitude" double precision,
	"attr_location_accuracy_m" real,
	"attr_location_age_ms" integer,
	"attr_location_altitude_m" double precision,
	"attr_location_speed_mps" double precision,
	"attr_location_speed_accuracy_mps" double precision,
	"attr_place_formatted_address" varchar(100),
	"attr_place_name" varchar(100),
	"attr_place_locality_type" varchar(100),
	"attr_place_country" varchar(100),
	"attr_place_country_code" varchar(2),
	"attr_place_region" varchar(100),
	"attr_place_subregion" varchar(100),
	"attr_place_subsubregion" varchar(100),
	"attr_place_postal_code" varchar(100),
	"attr_geohash6" varchar(6),
	"attr_geohash7" varchar(7),
	"attr_geohash8" varchar(8),
	"attr_location_vertical_accuracy_m" double precision,
	"id_location_type" smallint,
	"attr_private_ip_address" text,
	"attr_network_ipv4_address" text,
	"attr_network_ipv6_address" text,
	"attr_data_source_version" varchar(20),
	"val_signal_cqi" integer,
	"val_signal_rsrp_dbm" integer,
	"val_signal_rsrq_db" integer,
	"val_signal_rsrp_dbm2" integer,
	"val_signal_rssnr_db" integer,
	"val_signal_timing_advance_ts" integer,
	"val_signal_csi_snr_db" integer,
	"val_signal_csi_rsrq_db" integer,
	"val_signal_csi_rsrp_dbm" integer,
	"val_signal_ss_snr_dbm" integer,
	"val_signal_ss_rsrp_dbm" integer,
	"val_signal_ss_rsrq_db" integer,
	"attr_cell_bandwidths_khz" varchar(100),
	"id_cell_primary" bigint,
	"attr_cell_pci" integer,
	"attr_cell_lac" bigint,
	"attr_cell_tac" bigint,
	"is_dc_nr_restricted" boolean,
	"is_en_dc_available" boolean,
	"is_cell_nr_available" boolean,
	"attr_cell_nr_frequency_range" real,
	"attr_cell_frequency_channel" bigint,
	"attr_cell_frequency_channel_type" varchar(10),
	"attr_cell_technology_standard_name" varchar(50),
	"attr_wifi_frequency_mhz" integer,
	"attr_wifi_channel_width_id" smallint,
	"attr_wifi_standard" varchar(25),
	"id_wifi_standard" smallint,
	"attr_wifi_rssi_dbm" integer,
	"attr_wifi_max_supported_rx_link_speed_mbps" integer,
	"attr_wifi_max_supported_tx_link_speed_mbps" integer,
	"attr_wifi_rx_link_speed_mbps" integer,
	"attr_wifi_tx_link_speed_mbps" integer,
	"is_wifi_connected" boolean,
	"id_location_building" varchar(255),
	"val_indoor_confidence_level" real,
	"dt_foto" date
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "score" (
	"nu_ano_mes_rfrn" integer NOT NULL,
	"nm_oprd" varchar(50) NOT NULL,
	"cd_geo_hsh7" varchar(7) NOT NULL,
	"vl_vdeo_scre" double precision,
	"qt_ltra_vdeo_scre" integer,
	"vl_web_scre" double precision,
	"qt_ltra_web_scre" integer,
	"vl_nota_sped_scre" double precision,
	"qt_ltra_sped_scre" integer,
	"vl_cntv_scre" double precision,
	"no_arqv_orig" varchar(255),
	"dt_insr_vic" timestamp with time zone,
	"dt_atlz_vic" timestamp with time zone,
	"nu_cnro" integer,
	"ds_obs" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "geo_por_latlong" (
	"latitude" double precision,
	"longitude" double precision,
	"populacao_total_media" double precision,
	"total_de_domicilios_media" double precision,
	"total_trabalhadores_media" double precision,
	"renda_per_capita_media" double precision,
	"gastos_habitacao_dom_media" double precision,
	"gastos_transporte_dom_media" double precision,
	"gastos_saude_dom_media" double precision,
	"gastos_educacao_dom_media" double precision,
	"gastos_higiene_e_cuidados_pessoais_dom_media" double precision,
	"gastos_alimentacao_dom_media" double precision,
	"gastos_telefone_fixo_dom_media" double precision,
	"gastos_telefone_celular_dom_media" double precision,
	"gastos_pacote_3play_dom_media" double precision,
	"gastos_comunicacao_dom_media" double precision,
	"gastos_recreacao_e_cultura_dom_media" double precision,
	"gastos_viagens_dom_media" double precision,
	"propensao_seguro_saude_media" double precision,
	"propensao_seguro_vida_media" double precision,
	"propensao_seguro_residencial_media" double precision
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vivo_ftth_coverage" (
	"cod_geo" varchar(20) NOT NULL,
	"anomes" integer NOT NULL,
	"produto" varchar(20) NOT NULL,
	"tp_produto" varchar(10) NOT NULL,
	"uf" varchar(2) NOT NULL,
	"flg_loc" smallint NOT NULL,
	"x" double precision NOT NULL,
	"y" double precision NOT NULL,
	CONSTRAINT "vivo_ftth_coverage_cod_geo_anomes_pk" PRIMARY KEY("cod_geo","anomes")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vivo_mobile_erb" (
	"erb_casa" varchar(20) NOT NULL,
	"anomes" integer NOT NULL,
	"qtde_lnha_pos" integer NOT NULL,
	"qtde_lnha_ctrl" integer NOT NULL,
	"qtde_lnha_pre" integer NOT NULL,
	"x" double precision NOT NULL,
	"y" double precision NOT NULL,
	CONSTRAINT "vivo_mobile_erb_erb_casa_anomes_pk" PRIMARY KEY("erb_casa","anomes")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "geohash_cell" (
	"geohash_id" varchar(12) PRIMARY KEY NOT NULL,
	"precision" smallint NOT NULL,
	"center_lat" double precision NOT NULL,
	"center_lng" double precision NOT NULL,
	"geom" text,
	"neighborhood" varchar(100),
	"city" varchar(100) NOT NULL,
	"state" varchar(2) NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "benchmark_config" (
	"id" serial PRIMARY KEY NOT NULL,
	"key" varchar(50) NOT NULL,
	"scope" "benchmark_scope" NOT NULL,
	"region" varchar(100),
	"value" numeric(8, 3) NOT NULL,
	"period_date" date,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "user_session" (
	"user_id" varchar(255) PRIMARY KEY NOT NULL,
	"state" jsonb NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
